# Generated by Django 6.0.6 on 2026-06-22 14:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='accreditation_certificate',
            field=models.FileField(blank=True, null=True, upload_to='clinic_docs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'], message='Only jpg, jpeg, png files are allowed.')]),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='address',
            field=models.TextField(default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='license_number',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='phone',
            field=models.CharField(default='', max_length=20, validators=[django.core.validators.RegexValidator(message='Provide a valid phone number.', regex='^\\+?1?\\d{9,13}$')]),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='proof_of_address',
            field=models.FileField(blank=True, null=True, upload_to='clinic_docs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'], message='Only jpg, jpeg, png files are allowed.')]),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='tax_id',
            field=models.CharField(default='', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(13), django.core.validators.RegexValidator(message='This field must contain digits only.', regex='^\\d+$')]),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='verification_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
